### ISSUE TITLE
Screenshot

### ISSUE THREAD

**Issue by pinggod** [pinggod/hexo-theme-apollo#1]
![apollo](https://cloud.githubusercontent.com/assets/9530963/11295742/8f3d451a-8fa8-11e5-90d2-397af60a992d.png)

**Comment by hbqi207c** [comment]
...more进去标题显示有个“#”，是bug还是本来就这样的

**Comment by pinggod** [comment]
@hbqi207c 

特意用来标识标题的

**Comment by hbqi207c** [comment]
神速啊，谢谢回答!!

**Comment by pinggod** [comment]
在 Markdown 文件中添加如下结构，可以显示警告框：

```html
<div class="tip">
    预处理器很强大，但它只是编写 CSS 的辅助工具。出于对扩展和维护等方面的考虑，在大型项目中必要使用预处理器构建 CSS；但是对于小型项目，原生的 CSS 可能是一种更好的选择。不要肆意使用预处理器！
</div>
```

效果如下：

<img width="841" alt="2015-11-24 14 40 18" src="https://cloud.githubusercontent.com/assets/9530963/11359678/489a510c-92b9-11e5-9256-341cef6999b6.png">

**Comment by pinggod** [comment]
![2016-02-13 16 02 37](https://cloud.githubusercontent.com/assets/9530963/13026670/6ab47e38-d26b-11e5-9fef-4103e866b555.png)

**Comment by pinggod** [comment]
![2016-02-13 17 26 54](https://cloud.githubusercontent.com/assets/9530963/13026956/08e76eca-d277-11e5-8bfc-2e80cea20a0d.png)
