### ISSUE TITLE
Does Apollo support tags and categories?

### ISSUE THREAD

**Issue by markindev** [pinggod/hexo-theme-apollo#17]

**Comment by hongweiyi** [comment]
@markindev I've achieved tag cloud in my blog [yihongwei.com](http://yihongwei.com/tags/), but haven't create a pull request. 

[code repo](https://github.com/hongweiyi/hexo-theme-apollo)

**Comment by pinggod** [comment]
@markindev 

There is no immediate plans to support tag and categories module.

In fact, coding is not the hardest work but finding or creating great design prototypes is.

**Comment by markindev** [comment]
Got it. Thanks.
