### ISSUE TITLE
怎么添加Disqus呢？

### ISSUE THREAD

**Issue by JunyuMu** [pinggod/hexo-theme-apollo#2]
而且favicon貌似没有生效

**Comment by pinggod** [comment]
设置 favicon 时，需要将 favicon 文件置于 `themes/apollo/source/` 目录之下，然后设置 `themes/_config.yml` 中的 `favicon` 配置，比如 favicon 文件名为 `abc.xyz`，则 `themes/_config.yml` 中 `favicon: /abc.xyz`（这里使用的是绝对路径，abc 代表文件名，xyz 代表扩展名）。如果还有其他错误，请参考 chrome 控制台的提示。

此外，不支持评论系统，比如 disqus / 多说等。

**Comment by JunyuMu** [comment]
@pinggod 
我把favicon挡在`img`的目录里，加了路径`/img/favicon.png`但是并没有用，我看了NetWork的请求，没有favicon。

之后会添加评论吧？

**Comment by pinggod** [comment]
@JunyuMu 

在浏览器尝试一下是否可以链接到 favicon，比如 `http://localhost:[port]/img/favicon.png`（这里的 port 指代监听端口），然后根据 chrome 控制台的反馈进行调试。

引用 disqus 等第三方的评论系统是比较简单的一件事，不过我想让 apollo 的风格尽量简洁一些，暂时没有添加第三方评论的想法。你可以 fork 这个项目，做自己的一些定制。可能下一个主题或者在 Dribbble 上看到设计感十足的评论样式时，我才会添加第三方评论……

**Comment by JunyuMu** [comment]
@pinggod 
浏览器输入地址可以访问到favicon。另，我看你的DEMO，favicon也没有加载。

**Comment by JunyuMu** [comment]
@pinggod 
可能是缓存的原因。

**Comment by pinggod** [comment]
@JunyuMu 

刚刚发现是模板的设置问题，已更新代码
