### ISSUE TITLE
关于Browsersync

### ISSUE THREAD

**Issue by Lwxiang** [pinggod/hexo-theme-apollo#8]
web跑起来之后，右上角一直会出现connect to browsersync和disconnect to browsersync

并且有时候会一直不断地自我刷新

这个是hexo-browsersync插件导致的吗，请问如何解决

**Comment by pinggod** [comment]
这是一个文件更改后同步刷新的 Hexo 插件，通过 `npm uninstall --save hexo-browsersync` 卸载。

项目介绍：[https://github.com/hexojs/hexo-browsersync](https://github.com/hexojs/hexo-browsersync)

**Comment by Lwxiang** [comment]
OK.
