### ISSUE TITLE
字体问题

### ISSUE THREAD

**Issue by Lwxiang** [pinggod/hexo-theme-apollo#9]
FireFox下字体变现良好，到了Chrome就成了宋体了=_=。

**Comment by pinggod** [comment]
@Lwxiang 

抱歉，我这边只有 mac，无法复现问题。

主题内已经配置了 gulp 构建环境，可以自由修改 scss 文件，然后使用 `gulp sass` 重新编译样式文件。有关字体的样式在 `base.scss` 文件中。
